# Generated by Django 2.2 on 2021-07-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srtvs_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='release_date',
            new_name='releaseDate',
        ),
    ]
